Remove argument from helm install command
Helm no longer accepts the `--name` argument, but rather want you to input the name directly.

```
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"xxxx", GitTreeState:"dirty", GoVersion:"go1.15.4"}

$ helm install --name grafana --namespace infra  grafana/grafana
Error: unknown flag: --name

$ helm install grafana --namespace infra grafana/grafana
NAME: grafana
LAST DEPLOYED: Mon Nov 23 19:04:47 2020
NAMESPACE: infra
STATUS: deployed
```

Signed-off-by: Simon Aronsson <simme@arcticbit.se>