Yaml numbers in grafana.ini break templating
If grafana.ini in grafana/values.yaml contains a number field,
it causes helm templating to fail.
To test this, checkout latest and add grafana.ini.server.http_port: 3000 to values.yaml,
and try and render the template locally. Helm gives the following error:

```
❯ helm template charts/grafana --output-dir rendered --name-template=release-name
Error: template: grafana/templates/deployment.yaml:36:28: executing "grafana/templates/deployment.yaml" at <include "grafana.configData" .>: error calling include: template: grafana/templates/_config.tpl:34:23: executing "grafana.configData" at <$elemVal>: wrong type for value; expected string; got json.Number
```

Helm Info:
```
❯ helm version
version.BuildInfo{Version:"v3.18.0", GitCommit:"cc58e3f5a3aa615c6a86275e6f4444b5fdd3cc4e", GitTreeState:"clean", GoVersion:"go1.24.3"}
```

Even though we check if the field is a string, this is a Helm String but the
field is a yaml number, leading to the confusion. Ensuring we convert all Helm
strings to yaml strings ensures we do not hit the issue.

Signed-off-by: Eoin Farrell <me@eoinfarrell.dev>